[build-system]
requires = ["setuptools>=42", "wheel", "cmake>=3.12", "ninja"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]
